=== dgricci/xml-1a/exos/stagiaires.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT stagiaires (personne+,employeurs,lieuxDeTravail)>
<!ELEMENT personne (fonction)>
<!ATTLIST personne
          nom CDATA #REQUIRED
          prenom CDATA #REQUIRED
          service IDREF #REQUIRED
          lieu IDREF #REQUIRED
>
<!ELEMENT fonction (#PCDATA)>
<!ELEMENT employeurs (employeur+)>
<!ELEMENT employeur (direction+)>
<!ATTLIST employeur
          nom ID #REQUIRED
>
<!ELEMENT direction (service+)>
<!ATTLIST direction
          nom ID #REQUIRED
>
<!ELEMENT service EMPTY>
<!ATTLIST service
          nom ID #REQUIRED
          nbAgents CDATA #IMPLIED
>
<!ELEMENT lieuxDeTravail (lieuDeTravail+)>
<!ELEMENT lieuDeTravail (#PCDATA)>
<!ATTLIST lieuDeTravail
          nom ID #REQUIRED
>

=== dgricci/xml-1a/exos/stagiaires.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE stagiaires SYSTEM "stagiaires.dtd">
<stagiaires>
    <personne nom="NOM1" prenom="PRÉNOM1" service="SERVICE1" lieu="LIEU1">
        <fonction>FONCTION1</fonction>
    </personne>
    <personne nom="NOM2" prenom="PRÉNOM2" service="SERVICE2" lieu="LIEU2">
        <fonction>FONCTION2</fonction>
    </personne>
    <employeurs>
        <employeur nom="IGN">
            <direction nom="DIRECTION1">
                <service nom="SERVICE1" nbAgents="1"/>
            </direction>
            <direction nom="DIRECTION2">
                <service nom="SERVICE2" nbAgents="1"/>
            </direction>
        </employeur>
    </employeurs>
    <lieuxDeTravail>
        <lieuDeTravail nom="LIEU1">
rue
code postal ville
        </lieuDeTravail>
        <lieuDeTravail nom="LIEU2">
rue
code postal ville
        </lieuDeTravail>
    </lieuxDeTravail>
</stagiaires>
